# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Spring配置
spring:
  application:
    name: WildNest
  
  # HTTP编码配置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
  # 消息转换器配置
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  
  # 数据源配置 - 使用远程MySQL数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pppnas.top:9009/wildnest_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: wildnest_app
    password: fOxedteXJ8EIAU7OFPAV
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1
      validation-query-timeout: 30
      keep-alive: true
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
  

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# MyBatis-Plus配置
mybatis-plus:
  type-aliases-package: com.HuangYe.WildNest.entity
  # 禁用XML映射文件扫描，使用注解方式
  mapper-locations: 
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: test-access-key-id
    access-key-secret: test-access-key-secret
    bucket-name: test-bucket-name

# SpringDoc OpenAPI配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.HuangYe.WildNest.controller

# 日志配置
logging:
  level:
    root: info
    com.HuangYe.WildNest: debug
  file:
    name: logs/wildnest.log